name: CI
on: [push]
jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install
        run: yarn
      - name: Build
        run: yarn build:test
      - name: Test
        run: yarn test
      - name: Lint
        run: yarn lint
      - id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true
      - name: Setup publish token
        if: steps.check.outputs.changed == 'true' && github.ref == 'refs/heads/master'
        run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish
        if: steps.check.outputs.changed == 'true' && github.ref == 'refs/heads/master'
        run: yarn publish
